### ISSUE TITLE
Problem: Validation failed: user is invalid

### ISSUE THREAD

**Issue by andriuski** [eyp/redmine_spent_time#116]
Hi,

have a bitnami VM image of Redmine, installed the plugin. Everything functions well, except when I open the Spent time page and try to create a spent time entry. I get "Validation failed: User is invalid" after I hit save.
![paveikslas](https://user-images.githubusercontent.com/22753698/88639905-f96c9900-d0c5-11ea-951a-6a1050dbfb5e.png)

CLI log shows the same:
![paveikslas](https://user-images.githubusercontent.com/22753698/88639981-13a67700-d0c6-11ea-9a88-c9d1801c10f3.png)
Saving time entry and the validation failed: user is invalid.

Can somebody point me to where the problem is or at least where to start looking for it? I have rulled out permissions as all of the boxes are checked and users are assigned to projects/tasks, plugin installation did go well.  Not sure what else there could be.

Thanks

Andrius

**Comment by eyp** [comment]
If it’s the last version of Redmine, it’s already reported that the plugin doesn’t work. I’ve to fix it, but unfortunately I’m on holidays right now.

**Comment by andriuski** [comment]
Yes, it is Redmine 4. Check with friends on their production Redmine 4 wth the latest plugin - same issue.

Eagerly waiting for the fix.

A.

**Comment by shazada** [comment]
We have the same issue, just upgraded our environment and can't use it anymore.
Version 4.1.1.stable

**Comment by eyp** [comment]
Ok, just installed new version of Redmine on a new computer. Will fix it ASAP.

**Comment by eyp** [comment]
Fixed in new version 4.1.0

**Comment by shazada** [comment]
Thanks!

**Comment by vpetyov** [comment]
Hi I have this version 
![image](https://user-images.githubusercontent.com/6897590/202387385-f556d709-ad5b-4282-b90c-25f8f6fad675.png)

And the issue is still present. @eyp Please advise.
